# Generated by Django 5.1.4 on 2024-12-31 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlanks',
            fields=[
                ('QN', models.AutoField(primary_key=True, serialize=False)),
                ('question_problem', models.TextField()),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('QN', models.AutoField(primary_key=True, serialize=False)),
                ('question_problem', models.TextField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QN_type', models.CharField(choices=[('MCQ', 'Mcq'), ('FIB', 'Fib'), ('SQL', 'Sql')], max_length=10)),
                ('status', models.CharField(choices=[('solved', 'Solved'), ('unsolved', 'Unsolved'), ('attempted', 'Attempted')], max_length=10)),
                ('QN', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SQLQueries',
            fields=[
                ('QN', models.AutoField(primary_key=True, serialize=False)),
                ('problem', models.TextField()),
                ('queries', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('registration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_solved', models.IntegerField(default=0)),
                ('login_streak', models.IntegerField(default=0)),
                ('hard_problem_solved', models.IntegerField(default=0)),
                ('easy_problem_solved', models.IntegerField(default=0)),
                ('medium_problem_solved', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='data.user')),
            ],
        ),
    ]
