# Generated by Django 5.2 on 2025-04-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_stats_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserCustom',
        ),
    ]
